---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Event/Subscriber}'

    # Controller
    IDCI\Bundle\PaymentBundle\Controller\PaymentGatewayController:
        arguments:
            $logger: '@monolog.logger.payment'

    # Manager
    Doctrine\Common\Persistence\ObjectManager: null

    IDCI\Bundle\PaymentBundle\Manager\DoctrineTransactionManager:
        arguments:
            $om: '@?doctrine.orm.entity_manager'

    IDCI\Bundle\PaymentBundle\Manager\PaymentManager:
        arguments:
            $om: '@?doctrine.orm.entity_manager'
            $paymentGatewayConfigurations: '%idci_payment.gateway_configurations%'

    IDCI\Bundle\PaymentBundle\Manager\TransactionManagerInterface: '@IDCI\Bundle\PaymentBundle\Manager\DoctrineTransactionManager'

    # Subscriber

    IDCI\Bundle\PaymentBundle\Event\Subscriber\TransactionManagerEventSubscriber:
        arguments:
            $transactionManager: '@IDCI\Bundle\PaymentBundle\Manager\TransactionManagerInterface'

    IDCI\Bundle\PaymentBundle\Event\Subscriber\LoggerTransactionEventSubscriber:
        arguments:
            $logger: '@monolog.logger.payment'
            $enabled: '%idci_payment.enabled_logger_subscriber%'

    # Payment Gateways

    IDCI\Bundle\PaymentBundle\Gateway\StripePaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: stripe }

    IDCI\Bundle\PaymentBundle\Gateway\PaypalPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: paypal }

    idci_payment.gateways.mercanet_json:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsJsonPaymentGateway
        arguments:
            $serverHostName: '%idci_payment.mercanet.server_host_name%'
        tags:
            - { name: idci_payment.gateways, alias: mercanet_json_atos_sips }

    idci_payment.gateways.sogenactif_json:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsJsonPaymentGateway
        arguments:
            $serverHostName: '%idci_payment.sogenactif.server_host_name%'
        tags:
            - { name: idci_payment.gateways, alias: sogenactif_json_atos_sips }

    idci_payment.gateways.mercanet_post:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsPostPaymentGateway
        arguments:
            $serverHostName: '%idci_payment.mercanet.server_host_name%'
        tags:
            - { name: idci_payment.gateways, alias: mercanet_post_atos_sips }

    idci_payment.gateways.sogenactif_post:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsPostPaymentGateway
        arguments:
            $serverHostName: '%idci_payment.sogenactif.server_host_name%'
        tags:
            - { name: idci_payment.gateways, alias: sogenactif_post_atos_sips }

    idci_payment.gateways.sogenactif_bin:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsBinPaymentGateway
        arguments:
            $pathfile: "%idci_payment.sogenactif_bin.pathfile_path%"
            $requestBinPath: "%idci_payment.atos_sips_bin.request_bin_path%"
            $responseBinPath: "%idci_payment.atos_sips_bin.response_bin_path%"
        tags:
            - { name: idci_payment.gateways, alias: sogenactif_bin_atos_sips }

    idci_payment.gateways.scellius_bin:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsBinPaymentGateway
        arguments:
            $pathfile: "%idci_payment.scellius_bin.pathfile_path%"
            $requestBinPath: "%idci_payment.atos_sips_bin.request_bin_path%"
            $responseBinPath: "%idci_payment.atos_sips_bin.response_bin_path%"
        tags:
            - { name: idci_payment.gateways, alias: scellius_bin_atos_sips }

    idci_payment.gateways.mercanet_bin:
        class: IDCI\Bundle\PaymentBundle\Gateway\AtosSipsBinPaymentGateway
        arguments:
            $pathfile: "%idci_payment.mercanet_bin.pathfile_path%"
            $requestBinPath: "%idci_payment.atos_sips_bin.request_bin_path%"
            $responseBinPath: "%idci_payment.atos_sips_bin.response_bin_path%"
        tags:
            - { name: idci_payment.gateways, alias: mercanet_bin_atos_sips }

    IDCI\Bundle\PaymentBundle\Gateway\PayboxPaymentGateway:
        arguments:
            $serverHostName: '%idci_payment.paybox.server_host_name%'
            $keyPath: '%idci_payment.paybox.key_path%'
            $publicKeyUrl: '%idci_payment.paybox.public_key_url%'
        tags:
            - { name: idci_payment.gateways, alias: paybox }

    IDCI\Bundle\PaymentBundle\Gateway\OgonePaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: ogone }

    IDCI\Bundle\PaymentBundle\Gateway\MoneticoPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: monetico }

    IDCI\Bundle\PaymentBundle\Gateway\PayPlugPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: payplug }

    IDCI\Bundle\PaymentBundle\Gateway\SystemPayPaymentGateway:
        arguments:
            $serverUrl: '%idci_payment.systempay.server_url%'
        tags:
            - { name: idci_payment.gateways, alias: systempay }

    IDCI\Bundle\PaymentBundle\Gateway\SofincoPaymentGateway:
        arguments:
            $serverUrl: '%idci_payment.sofinco.server_url%'
        tags:
            - { name: idci_payment.gateways, alias: sofinco }

    IDCI\Bundle\PaymentBundle\Gateway\EurekaPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: eureka }

    # Payment Gateway Clients

    IDCI\Bundle\PaymentBundle\Gateway\Client\EurekaPaymentGatewayClient:
        arguments:
            $serverHostName: '%idci_payment.eureka.server_host_name%'
        calls:
            - [setCache, ['@?cache.idci_payment']]
