idci_payment_gateway_transaction_notification:
    controller: IDCI\Bundle\PaymentBundle\Controller\PaymentGatewayController::notifyTransaction
    path: /payment-gateway/{configuration_alias}/notify-transaction
    methods: ['GET', 'POST']